services:
  charting-service:
    image: "getorganized-charting-service"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./generated
        target: /usr/app/generated
      - type: bind
        source: ./config
        target: /usr/app/config
        read_only: true
