services:
  charting-service:
    image: "getorganized-charting-service"
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: generated-graphs
        target: /usr/app/generated
      - type: bind
        source: ./config
        target: /usr/app/config
        read_only: true

  api-and-frontend-service:
    image: "getorganized-api-and-frontend-service"
    ports:
      - "8009:80"
    volumes:
      - type: volume
        source: generated-graphs
        target: /var/www/html/generated

volumes:
  generated-graphs:
